export { default as DashboardPageTitle } from "./DashboardPageTitle";
export { default as RoleLabel } from "./RoleLabel";
export { default as Announcement } from "./Announcement";
export { default as LiveReport } from "./LiveReport";
export { default as Profile } from "./Profile";
export { default as Statistics } from "./Statistics";
export { default as Weather } from "./Weather";
export { default as UserTable } from "./UserTable";
export { default as StudentTable } from "./StudentTable";
export { default as AddUser } from "./AddUser";
export { default as EditUser } from "./EditUser";
export { default as AddStudent } from "./AddStudent";
export { default as EditStudent } from "./EditStudent";
export { default as ReportPage } from "./ReportPage";
export { default as AnnouncementPage} from "./AnnouncementPage";
export { default as ClassPage} from "./ClassPage";
export { default as LiveReportPage } from "./LiveReportPage";
export { default as ResetPassword } from "./ResetPassword";
export { default as DetailReport} from "./DetailReport";
export { default as MenuNotFound} from "./MenuNotFound";
export { default as LiveChat} from "./LiveChat";
